/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 *  ianjuta-terminal.h -- Autogenerated from libanjuta.idl
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#ifndef _IANJUTA_TERMINAL_H_
#define _IANJUTA_TERMINAL_H_

#include <glib-object.h>
#include <sys/types.h>

G_BEGIN_DECLS

#define IANJUTA_TYPE_TERMINAL (ianjuta_terminal_get_type ())
#define IANJUTA_TERMINAL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IANJUTA_TYPE_TERMINAL, IAnjutaTerminal))
#define IANJUTA_IS_TERMINAL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IANJUTA_TYPE_TERMINAL))
#define IANJUTA_TERMINAL_GET_IFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), IANJUTA_TYPE_TERMINAL, IAnjutaTerminalIface))

#define IANJUTA_TERMINAL_ERROR ianjuta_terminal_error_quark()

typedef struct _IAnjutaTerminal IAnjutaTerminal;
typedef struct _IAnjutaTerminalIface IAnjutaTerminalIface;


struct _IAnjutaTerminalIface {
	GTypeInterface g_iface;
	
	/* Signal */
	void (*child_exited) (IAnjutaTerminal *obj, gint pid,  gint status);

	pid_t (*execute_command) (IAnjutaTerminal *obj, const gchar* directory,  const gchar *command,  gchar **environment, GError **err);

};


GQuark ianjuta_terminal_error_quark     (void);
GType  ianjuta_terminal_get_type        (void);

pid_t ianjuta_terminal_execute_command (IAnjutaTerminal *obj, const gchar* directory,  const gchar *command,  gchar **environment, GError **err);


G_END_DECLS

#endif
