/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 *  ianjuta-todo.h -- Autogenerated from libanjuta.idl
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#ifndef _IANJUTA_TODO_H_
#define _IANJUTA_TODO_H_

#include <glib-object.h>
#include <gio/gio.h>

G_BEGIN_DECLS

#define IANJUTA_TYPE_TODO (ianjuta_todo_get_type ())
#define IANJUTA_TODO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IANJUTA_TYPE_TODO, IAnjutaTodo))
#define IANJUTA_IS_TODO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IANJUTA_TYPE_TODO))
#define IANJUTA_TODO_GET_IFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), IANJUTA_TYPE_TODO, IAnjutaTodoIface))

#define IANJUTA_TODO_ERROR ianjuta_todo_error_quark()

typedef struct _IAnjutaTodo IAnjutaTodo;
typedef struct _IAnjutaTodoIface IAnjutaTodoIface;


struct _IAnjutaTodoIface {
	GTypeInterface g_iface;
	

	void (*load) (IAnjutaTodo *obj, GFile *file, GError **err);

};


GQuark ianjuta_todo_error_quark     (void);
GType  ianjuta_todo_get_type        (void);

void ianjuta_todo_load (IAnjutaTodo *obj, GFile *file, GError **err);


G_END_DECLS

#endif
