/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 *  ianjuta-wizard.h -- Autogenerated from libanjuta.idl
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#ifndef _IANJUTA_WIZARD_H_
#define _IANJUTA_WIZARD_H_

#include <glib-object.h>

G_BEGIN_DECLS

#define IANJUTA_TYPE_WIZARD (ianjuta_wizard_get_type ())
#define IANJUTA_WIZARD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IANJUTA_TYPE_WIZARD, IAnjutaWizard))
#define IANJUTA_IS_WIZARD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IANJUTA_TYPE_WIZARD))
#define IANJUTA_WIZARD_GET_IFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), IANJUTA_TYPE_WIZARD, IAnjutaWizardIface))

#define IANJUTA_WIZARD_ERROR ianjuta_wizard_error_quark()

typedef struct _IAnjutaWizard IAnjutaWizard;
typedef struct _IAnjutaWizardIface IAnjutaWizardIface;


struct _IAnjutaWizardIface {
	GTypeInterface g_iface;
	

	void (*activate) (IAnjutaWizard *obj, GError **err);

};


GQuark ianjuta_wizard_error_quark     (void);
GType  ianjuta_wizard_get_type        (void);

void ianjuta_wizard_activate (IAnjutaWizard *obj, GError **err);


G_END_DECLS

#endif
