/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 *  ianjuta-loader.h -- Autogenerated from libanjuta.idl
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#ifndef _IANJUTA_LOADER_H_
#define _IANJUTA_LOADER_H_

#include <glib-object.h>
#include <libanjuta/anjuta-plugin.h>

G_BEGIN_DECLS

#define IANJUTA_TYPE_LOADER (ianjuta_loader_get_type ())
#define IANJUTA_LOADER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IANJUTA_TYPE_LOADER, IAnjutaLoader))
#define IANJUTA_IS_LOADER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IANJUTA_TYPE_LOADER))
#define IANJUTA_LOADER_GET_IFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), IANJUTA_TYPE_LOADER, IAnjutaLoaderIface))

#define IANJUTA_LOADER_ERROR ianjuta_loader_error_quark()

typedef struct _IAnjutaLoader IAnjutaLoader;
typedef struct _IAnjutaLoaderIface IAnjutaLoaderIface;


struct _IAnjutaLoaderIface {
	GTypeInterface g_iface;
	

	GList* (*find_plugins) (IAnjutaLoader *obj, GError **err);

};


GQuark ianjuta_loader_error_quark     (void);
GType  ianjuta_loader_get_type        (void);

GList* ianjuta_loader_find_plugins (IAnjutaLoader *obj, GError **err);


G_END_DECLS

#endif
