/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 *  ianjuta-editor-cell-style.h -- Autogenerated from libanjuta.idl
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#ifndef _IANJUTA_EDITOR_CELL_STYLE_H_
#define _IANJUTA_EDITOR_CELL_STYLE_H_

#include <glib-object.h>
#include <libanjuta/interfaces/ianjuta-editor-cell.h>

G_BEGIN_DECLS

#define IANJUTA_TYPE_EDITOR_CELL_STYLE (ianjuta_editor_cell_style_get_type ())
#define IANJUTA_EDITOR_CELL_STYLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IANJUTA_TYPE_EDITOR_CELL_STYLE, IAnjutaEditorCellStyle))
#define IANJUTA_IS_EDITOR_CELL_STYLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IANJUTA_TYPE_EDITOR_CELL_STYLE))
#define IANJUTA_EDITOR_CELL_STYLE_GET_IFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), IANJUTA_TYPE_EDITOR_CELL_STYLE, IAnjutaEditorCellStyleIface))

#define IANJUTA_EDITOR_CELL_STYLE_ERROR ianjuta_editor_cell_style_error_quark()

typedef struct _IAnjutaEditorCellStyle IAnjutaEditorCellStyle;
typedef struct _IAnjutaEditorCellStyleIface IAnjutaEditorCellStyleIface;


struct _IAnjutaEditorCellStyleIface {
	IAnjutaEditorCellIface g_iface;
	

	gchar* (*get_background_color) (IAnjutaEditorCellStyle *obj, GError **err);
	gchar* (*get_color) (IAnjutaEditorCellStyle *obj, GError **err);
	gchar* (*get_font_description) (IAnjutaEditorCellStyle *obj, GError **err);

};


GQuark ianjuta_editor_cell_style_error_quark     (void);
GType  ianjuta_editor_cell_style_get_type        (void);

gchar* ianjuta_editor_cell_style_get_background_color (IAnjutaEditorCellStyle *obj, GError **err);

gchar* ianjuta_editor_cell_style_get_color (IAnjutaEditorCellStyle *obj, GError **err);

gchar* ianjuta_editor_cell_style_get_font_description (IAnjutaEditorCellStyle *obj, GError **err);


G_END_DECLS

#endif
