/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 *  ianjuta-snippets-manager.h -- Autogenerated from libanjuta.idl
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#ifndef _IANJUTA_SNIPPETS_MANAGER_H_
#define _IANJUTA_SNIPPETS_MANAGER_H_

#include <glib-object.h>

G_BEGIN_DECLS

#define IANJUTA_TYPE_SNIPPETS_MANAGER (ianjuta_snippets_manager_get_type ())
#define IANJUTA_SNIPPETS_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IANJUTA_TYPE_SNIPPETS_MANAGER, IAnjutaSnippetsManager))
#define IANJUTA_IS_SNIPPETS_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IANJUTA_TYPE_SNIPPETS_MANAGER))
#define IANJUTA_SNIPPETS_MANAGER_GET_IFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), IANJUTA_TYPE_SNIPPETS_MANAGER, IAnjutaSnippetsManagerIface))

#define IANJUTA_SNIPPETS_MANAGER_ERROR ianjuta_snippets_manager_error_quark()

typedef struct _IAnjutaSnippetsManager IAnjutaSnippetsManager;
typedef struct _IAnjutaSnippetsManagerIface IAnjutaSnippetsManagerIface;


struct _IAnjutaSnippetsManagerIface {
	GTypeInterface g_iface;
	

	gboolean (*insert) (IAnjutaSnippetsManager *obj, const gchar* key,  gboolean editing_session, GError **err);

};


GQuark ianjuta_snippets_manager_error_quark     (void);
GType  ianjuta_snippets_manager_get_type        (void);

gboolean ianjuta_snippets_manager_insert (IAnjutaSnippetsManager *obj, const gchar* key,  gboolean editing_session, GError **err);


G_END_DECLS

#endif
