/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 *  ianjuta-editor-factory.h -- Autogenerated from libanjuta.idl
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#ifndef _IANJUTA_EDITOR_FACTORY_H_
#define _IANJUTA_EDITOR_FACTORY_H_

#include <glib-object.h>
#include <libanjuta/interfaces/ianjuta-editor.h>
#include <gio/gio.h>

G_BEGIN_DECLS

#define IANJUTA_TYPE_EDITOR_FACTORY (ianjuta_editor_factory_get_type ())
#define IANJUTA_EDITOR_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IANJUTA_TYPE_EDITOR_FACTORY, IAnjutaEditorFactory))
#define IANJUTA_IS_EDITOR_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IANJUTA_TYPE_EDITOR_FACTORY))
#define IANJUTA_EDITOR_FACTORY_GET_IFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), IANJUTA_TYPE_EDITOR_FACTORY, IAnjutaEditorFactoryIface))

#define IANJUTA_EDITOR_FACTORY_ERROR ianjuta_editor_factory_error_quark()

typedef struct _IAnjutaEditorFactory IAnjutaEditorFactory;
typedef struct _IAnjutaEditorFactoryIface IAnjutaEditorFactoryIface;


struct _IAnjutaEditorFactoryIface {
	GTypeInterface g_iface;
	

	IAnjutaEditor* (*new_editor) (IAnjutaEditorFactory *obj, GFile* file,  const gchar* filename, GError **err);

};


GQuark ianjuta_editor_factory_error_quark     (void);
GType  ianjuta_editor_factory_get_type        (void);

IAnjutaEditor* ianjuta_editor_factory_new_editor (IAnjutaEditorFactory *obj, GFile* file,  const gchar* filename, GError **err);


G_END_DECLS

#endif
