/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 *  ianjuta-editor-view.h -- Autogenerated from libanjuta.idl
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#ifndef _IANJUTA_EDITOR_VIEW_H_
#define _IANJUTA_EDITOR_VIEW_H_

#include <glib-object.h>
#include <libanjuta/interfaces/ianjuta-editor.h>

G_BEGIN_DECLS

#define IANJUTA_TYPE_EDITOR_VIEW (ianjuta_editor_view_get_type ())
#define IANJUTA_EDITOR_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IANJUTA_TYPE_EDITOR_VIEW, IAnjutaEditorView))
#define IANJUTA_IS_EDITOR_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IANJUTA_TYPE_EDITOR_VIEW))
#define IANJUTA_EDITOR_VIEW_GET_IFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), IANJUTA_TYPE_EDITOR_VIEW, IAnjutaEditorViewIface))

#define IANJUTA_EDITOR_VIEW_ERROR ianjuta_editor_view_error_quark()

typedef struct _IAnjutaEditorView IAnjutaEditorView;
typedef struct _IAnjutaEditorViewIface IAnjutaEditorViewIface;


struct _IAnjutaEditorViewIface {
	IAnjutaEditorIface g_iface;
	

	void (*create) (IAnjutaEditorView *obj, GError **err);
	gint (*get_count) (IAnjutaEditorView *obj, GError **err);
	void (*remove_current) (IAnjutaEditorView *obj, GError **err);

};


GQuark ianjuta_editor_view_error_quark     (void);
GType  ianjuta_editor_view_get_type        (void);

void ianjuta_editor_view_create (IAnjutaEditorView *obj, GError **err);

gint ianjuta_editor_view_get_count (IAnjutaEditorView *obj, GError **err);

void ianjuta_editor_view_remove_current (IAnjutaEditorView *obj, GError **err);


G_END_DECLS

#endif
