/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 *  ianjuta-glade.h -- Autogenerated from libanjuta.idl
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#ifndef _IANJUTA_GLADE_H_
#define _IANJUTA_GLADE_H_

#include <glib-object.h>

G_BEGIN_DECLS

#define IANJUTA_TYPE_GLADE (ianjuta_glade_get_type ())
#define IANJUTA_GLADE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IANJUTA_TYPE_GLADE, IAnjutaGlade))
#define IANJUTA_IS_GLADE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IANJUTA_TYPE_GLADE))
#define IANJUTA_GLADE_GET_IFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), IANJUTA_TYPE_GLADE, IAnjutaGladeIface))

#define IANJUTA_GLADE_ERROR ianjuta_glade_error_quark()

typedef struct _IAnjutaGlade IAnjutaGlade;
typedef struct _IAnjutaGladeIface IAnjutaGladeIface;


struct _IAnjutaGladeIface {
	GTypeInterface g_iface;
	

	void (*add_association) (IAnjutaGlade *obj, gchar *master,  gchar *slave, GError **err);

};


GQuark ianjuta_glade_error_quark     (void);
GType  ianjuta_glade_get_type        (void);

void ianjuta_glade_add_association (IAnjutaGlade *obj, gchar *master,  gchar *slave, GError **err);


G_END_DECLS

#endif
